# Generated by Django 5.2.4 on 2025-07-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('pub_date', models.DateField()),
                ('raw_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('issues', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.article')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallucination_score', models.IntegerField()),
                ('issues', models.JSONField()),
                ('summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_pipeline.summary')),
            ],
        ),
    ]
