# Generated by Django 5.2.4 on 2025-07-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0002_alter_summary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='hallucination_score',
            field=models.FloatField(help_text='Number of hallucinated claims; can be fractional'),
        ),
    ]
